config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'


  get '/pages/contact', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' } do
  resources :spheres, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :chatrooms, only: [:create]
    resources :bookings, only: [:new, :create, :index] do
      resources :reviews, only: [:new, :create]
    end
  end

  resources :chatrooms, only: [:index, :show,] do
  resources :messages, only: [:create]
  end
    # get 'index', to: 'meetings#index'

  resources :bookings, only: [:index, :destroy]

  resources :users, only: [:show] do
    member do
      post :follow
      post :unfollow
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :spheres
  has_many :bookings

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  attr_accessor :email, :password, :password_confirmation, :remember_me, :name

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
def facebook
  @user = User.from_omniauth(request.env['omniauth.auth'])
  if @user.persisted?
    sign_in_and_redirect @user, :event => :authentication
    set_flash_message(:notice, :success, :kind => 'Facebook') if is_navigational_format?
  else
    session['devise.facebook_data'] = request.env['omniauth.auth']
    redirect_to new_user_registration_url
  end
end

def failure
  redirect_to root_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :follow, :unfollow]

  # def index
  #   @users = User.where.not(id: current_user.id)
  # end

  def show
    authorize @user
    @chatrooms = Chatroom.joins(:sphere).where(user: current_user, spheres: {user: @user})
    @messages = Message.where(chatroom: @chatrooms)
  end

  def follow
    authorize @user
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow
    authorize @user
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render action: :follow }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<!-- _user.html.erb -->
<% if current_user.is_following?(user.id) %>
  <li data-user="<%= user.id %>">
    <%= link_to "unfollow", unfollow_user_path(user.id), method: :post, remote: true %>
  </li>
<% else %>
  <li data-user="<%= user.id %>">
  <%= link_to "follow", follow_user_path(user.id), method: :post, remote: true %>
  </li>
<% end %>

app/views/users/follow.js.erb
// follow.js.erb

function renderUser(userHTML) {
  const user = document.querySelector("[data-user='<%= @user.id %>']");
  user.outerHTML = userHTML;
}

renderUser('<%= j render @user %>');

app/views/users/show.html.erb
<!-- user/show.html.erb -->
<div class="edit-banner margin" style="background-color: $yellow, linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
  <% if @user == current_user %>
    <h3>You</h3>
  <% else %>
    <h3><%= @user.name %></h3>
  <% end %>
</div>
<img src="<%= @user.image %>" class="card-sphere-user avatar-bordered middle" style="height: 200px" alt="avatar of user" />


<%#= render @user %>
<!-- follow -->

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12-users padding-top" style="padding-top: 210px;">

      <button class="box button btn btn-yellow home middle" style="text-decoration: none; list-style-type: none"><%= render 'user', user: @user %></button>
      
      <div class="card-body d-flex justify-content-center" style="padding-top: 60px;">
        <%= link_to 'go back', sphere_path, class: 'btn btn-light' %>
      </div>
    </div>

<div class="container" style="padding-top: 0px; padding-bottom: 60px;">
<h1 style="font-size: 28px;"> all your messages with this user: </h1>

<%= render @messages %>

<%# @messages.each do |message| %>
  <%#= message %>
<%# end %>
</div>
</div>
</div>