config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'


  get '/pages/contact', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' } do
  resources :spheres, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :chatrooms, only: [:create]
    resources :bookings, only: [:new, :create, :index] do
      resources :reviews, only: [:new, :create]
    end
  end

  resources :chatrooms, only: [:index, :show,] do
  resources :messages, only: [:create]
  end
    # get 'index', to: 'meetings#index'

  resources :bookings, only: [:index, :destroy]

  resources :users, only: [:show] do
    member do
      post :follow
      post :unfollow
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice.downcase %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert.downcase %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">

  <div class="navbar-items">
    <%= link_to icon('fas', 'search'), root_path, class: "nav-item" %>
    <%= link_to icon('fas', 'plus'), new_sphere_path, class: "nav-item" %>
    <%= link_to icon('fas', 'calendar'), bookings_path, class: "nav-item" %>
    <%= link_to icon('fas', 'comments'), chatrooms_path, class: "nav-item" %>
    <%= link_to icon('fas', 'user'), pages_contact_path, class: "nav-item" %>
  </div>
</div>