config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'


  get '/pages/contact', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' } do
  resources :spheres, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :chatrooms, only: [:create]
    resources :bookings, only: [:new, :create, :index] do
      resources :reviews, only: [:new, :create]
    end
  end

  resources :chatrooms, only: [:index, :show,] do
  resources :messages, only: [:create]
  end
    # get 'index', to: 'meetings#index'

  resources :bookings, only: [:index, :destroy]

  resources :users, only: [:show] do
    member do
      post :follow
      post :unfollow
    end
  end
end

app/views/pages/contact.html.erb
<div class="edit-banner"> your profile </div>
<div class="my-4">

  <div class="profile-container">
    <% avatar_url = current_user.image || "http://placehold.it/30x30" %>
    <img src="<%= avatar_url%>" class="card-sphere-user avatar-bordered" alt="avatar of user" />

    <h3 class="profile-title">welcome back <%= current_user.name  %></h3>

    <% if user_signed_in? %>
          <!-- <div class="edit-banner"> log out </div> <%= current_user.name %>
          <% avatar_url = current_user.image || "http://placehold.it/30x30" %>
          <img src="<%= avatar_url%>" class="card-sphere-user avatar-bordered" alt="avatar of user" /> -->
          <%= link_to "logout", destroy_user_session_path, method: :delete, class: "dropdown-item text-center" %>
          <% else %>
          <div class="edit-banner"> log in </div>
          <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
          <% end %>

      </div>
  </div>

  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">
        spheres
      </a>
    </li>


    <li class="nav-item">
      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">
        followers
      </a>
    </li>
  </ul>



      <div class="container my-4">
        <h5 class="profile-spheres-count mb-3">you have <%= current_user.spheres.count  %> sphere(s)</h5>
        <% @spheres.each do |sphere| %>
        <div class="card-sphere-contact-page">


          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <% if sphere.photos.attached? %>
              <% sphere.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%='active' if index == 0 %>">
                <%= cl_image_tag photo.key, height: 250, width: 400, crop: :fill, class: "d-block w-100", alt: "pictures of the apartment" %>
              </div>
              <% end %>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <div class="sphere-content">
          <h4 class="profile-card-title"><%= link_to sphere.title.downcase, sphere_path(sphere) %></h4>
          <!-- <p><%= sphere.address.downcase  %></p> -->
          <p><%= sphere.description %></p>
          <!-- <p class="card-sphere-show-pricing"> cost per day: <%= sphere.cost_per_day %>€</p> -->


          <div class="d-flex justify-content-between" style="width: 100%;">


            <%= link_to 'edit', edit_sphere_path(sphere), class: 'btn-yellow' %>

            <% if policy(sphere).destroy? %>
            <%= link_to sphere_path(sphere), method: :delete, data: { confirm: 'are you sure?' }, class: 'btn-light btn-delete' do %>
            <i class="far fa-trash-alt"></i>
            <% end %>
            <% end %>
          </div>
          </div>
          </div>
          <% end %>

          </div>
        <br>

    <!-- <div class="card-sphere-show-contact">
      <p>you are following:</p>
      <ul>
        <% current_user.following.each do |following| %>
          <% avatar_url = following.image || "http://placehold.it/30x30" %>
          <img src="<%= avatar_url%>" class="card-sphere-user avatar-bordered" alt="avatar of user" />
          <%= link_to following.name, user_path(following) %>
        <% end %>
      </ul>
    </div> -->

    <!--   <div class="footer-links">
        <div class="btn-searchbar" id="whitelink"> <a href="mailto:hello@balconia.xyz">contact us via mail</a> </div>
        <a href="#"><i class="fab fa-github"></i></a> -
        <a href="#"><i class="fab fa-instagram"></i></a> -
        <a href="#"><i class="fab fa-facebook"></i></a> -
        <a href="mailto:hello@balconia.xyz">hello@balconia.xyz</a>
        <p><i class="fas fa-heart", color: yellow></i> share your thoughs! </p>
      </div> -->

app/views/pages/home.html.erb
<div class="card-sphere">
<div id="background-homepage">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="home-content text-center">

          <div class="box">

            <%= image_tag "illustration1.jpg", class:"home-image" %>

            <h1 style="font-size: 36px; font-weight: bold;">balconia</h1>
            <h3>find your ideal workplace</h3>
            <p>all the comfort of your own home <br> - only better!</p>

            <div class="form">
              <%= simple_form_for :search, url: spheres_path, method: :get do |f| %>
              <div class="search-form-control form-group" style="margin-bottom: 10px;">

              <%= form_tag spheres_path, method: :get do %>
              <%= text_field_tag :query,
                params[:query],
                class: "form-control string required",
                placeholder: "enter your city"
                %>
                <%= submit_tag "explore our spheres", class: "btn-searchbar", style: "margin-bottom: 0px;" %>
              <% end %>

              </div>
              <% end %>
              <div class="container d-flex justify-content-center">

              <button class="box button btn btn-light home" style="margin-top: 0;"><%= link_to "offer your sphere",  new_sphere_path %></button>


              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>