config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'


  get '/pages/contact', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' } do
  resources :spheres, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :chatrooms, only: [:create]
    resources :bookings, only: [:new, :create, :index] do
      resources :reviews, only: [:new, :create]
    end
  end

  resources :chatrooms, only: [:index, :show,] do
  resources :messages, only: [:create]
  end
    # get 'index', to: 'meetings#index'

  resources :bookings, only: [:index, :destroy]

  resources :users, only: [:show] do
    member do
      post :follow
      post :unfollow
    end
  end
end

app/models/sphere.rb
class Sphere < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos

  validates :title, presence: true, length: { minimum:4 }
  validates :address, presence: true, length: { minimum:1 }

  validates :cost_per_day, presence: true
  # validates :photos, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end

  # def freinds?(user_id)
  #   friends = Follow.find_by(follower_id: id, following_id: user_id)
  #   return true if friends
  # end
end

app/controllers/spheres_controller.rb
class SpheresController < ApplicationController
  before_action :set_sphere, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: [:show, :index, :list]

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def index

    @spheres = policy_scope(Sphere)

    # City search
    if params[:query].present?
      @spheres = @spheres.where('address ILIKE ?', "%#{params[:query]}%")
    elsif params[:search].present?
      search_params = params[:search].select { |key, value| value == 'true'}
      search_params = search_params.reject!{ |key| key == 'following'}
      # raise
      search_params.permit!
      @spheres = @spheres.where(search_params)

      if current_user.following.any? && params[:search][:following] == 'true'
        current_user.following.each do |following|
          # raise
          @spheres = @spheres.where(user_id: following.id)

        end
      end

    else
      @spheres = @spheres.all
    end

    # price filtering
    if params[:cost_per_day] == 'below 20'
      @spheres = policy_scope(Sphere).where("cost_per_day < 20")
    elsif params[:cost_per_day] == 'below 10'
      @spheres = policy_scope(Sphere).where("cost_per_day < 10")
    elsif params[:cost_per_day] == 'free'
      @spheres = policy_scope(Sphere).where("cost_per_day = 0")
    end

    # Follower filter
    # if params[:search]
    #   # current_user.following.each do |following|
    #   #   @spheres = policy_scope(Sphere).where(user_id: following)
    #   # end
    # end

    if @spheres.any?
      @markers = @spheres.geocoded.map do |sphere|
        {
          lat: sphere.latitude,
          lng: sphere.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { sphere: sphere })
        }
      end
    end

  end

  def show
    authorize @sphere
    @bookings = Booking.where(sphere: @sphere)
  end

  def new
    @sphere = Sphere.new

    authorize @sphere
  end

  def create
    @user = current_user
    @sphere = Sphere.new(sphere_params)
    @sphere.user = @user

    authorize @sphere

    if @sphere.save
      redirect_to sphere_path(@sphere), notice: 'saved successfully'
    else
      render :new
    end
  end

  def edit
    authorize @sphere
  end

  def update

    authorize @sphere

    if @sphere.update(sphere_params)
      redirect_to sphere_path(@sphere), notice: 'saved successfully'
    else
      render :edit
    end
  end

  def destroy
    @user = current_user
    @sphere = Sphere.find(params[:id])

    authorize @sphere

    @sphere.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to root_path, notice: 'deleted successfully'
  end

  private

  # strong params
  def sphere_params
    params.require(:sphere).permit(:title, :address, :description, :cost_per_day, :barbecue, :balcony, :garden, :terrace, :sunny, :highspeed_wifi, :plants, :quiet, :spacious_desk, :cozy, :pet_friendly, photos: [])
  end

  def set_sphere
    @sphere = Sphere.find(params[:id])
  end
end

app/views/spheres/_info_window.html.erb
  <div class="map-popup">
    <%= link_to sphere_path(sphere) do  %>
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <% if sphere.photos.attached? %>
                <% sphere.photos.each_with_index do |photo, index| %>
                  <div class="carousel-item <%='active' if index == 0 %>">
                    <%= cl_image_tag photo.key, height: 250, width: 400, crop: :fill, class: "d-block w-100", alt: "pictures of the apartment" %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <% end %>

    <div class="map-infos">

    <p class="green-text"><%= sphere.title %></p>
    <p><%= sphere.cost_per_day %>€</p>
    </div>

  </div>

app/views/spheres/edit.html.erb
<div class="edit-banner"> edit your sphere's details </div>
<div class="container my-4">
    <div id="edit-form">
      <div class="mt-3">
          <div class="col-12">
              <%= simple_form_for(@sphere) do |f| %>
                <div class="form-group">
                  <%= f.label :title, class: "lowercase" %>
                  <%= f.text_field :title, class: 'form-control', placeholder: ' Sunny rooftop terrace...' %>
                </div>
                <div class="form-group">
                  <%= f.label :description, class: "lowercase" %>
                  <%= f.text_field :description, class: 'form-control', placeholder: ' Enjoy the warm summer vibes...' %>
                </div>
                <div class="form-group">
                  <%= f.label :address, class: "lowercase" %>
                  <%= f.text_area :address, class: 'form-control', placeholder: ' 1 Paradise Road, Berlin...' %>
                </div>
                  <div class="form-group">
                  <%= f.label :cost_per_day, class: "lowercase" %>
                  <%= f.number_field :cost_per_day, class: 'form-control', placeholder: ' ...€' %>
                </div>

                <div class="form-group lowercase">
                    <%= f.label :photos %>
                    <%= f.input :photos, as: :file, input_html: { multiple: true }, class: 'form-control', label: false %>
                </div>

                <div class="form-check">
                  <%= f.check_box :balcony, class:"form-check-input" %>
                  <%= f.label :balcony, class: "lowercase form-check-label" %>
                </div>
                <div class="form-check">
                  <%= f.check_box :garden, class:"form-check-input" %>
                  <%= f.label :garden, class: "lowercase form-check-label" %>
                </div>
                <div class="form-check">
                  <%= f.check_box :terrace, class:"form-check-input" %>
                  <%= f.label :terrace, class: "lowercase form-check-label" %>
                </div>
                <div class="form-check">
                  <%= f.check_box :sunny, class:"form-check-input" %>
                  <%= f.label :sunny, class: "lowercase form-check-label" %>
                </div>
                <div class="form-check">
                  <%= f.check_box :highspeed_wifi, class:"form-check-input" %>
                  <%= f.label :highspeed_wifi, class: "lowercase form-check-label" %>
                </div>
                <div class="form-check">
                  <%= f.check_box :plants, class:"form-check-input" %>
                  <%= f.label :plants, class: "lowercase form-check-label" %>
                </div>

                <div class="form-check">
                  <%= f.check_box :quiet, class:"form-check-input" %>
                  <%= f.label :quiet, class: "lowercase form-check-label" %>
                </div>

                <div class="form-check">
                  <%= f.check_box :spacious_desk, class:"form-check-input" %>
                  <%= f.label :spacious_desk, class: "lowercase form-check-label" %>
                </div>

                <div class="form-check">
                  <%= f.check_box :barbecue, class:"form-check-input" %>
                  <%= f.label :barbecue, class: "lowercase form-check-label" %>
                </div>

                <div class="form-check">
                  <%= f.check_box :cozy, class:"form-check-input" %>
                  <%= f.label :cozy, class: "lowercase form-check-label" %>
                </div>

                <div class="form-check">
                  <%= f.check_box :pet_friendly, class:"form-check-input" %>
                  <%= f.label :pet_friendly, class: "lowercase form-check-label" %>
                </div>

                <div class="mt-3">
                  <div class="d-flex justify-content-around">
                    <%= f.submit "edit", class: 'btn-yellow' %>
                    <%= link_to 'cancel', '#', class: 'btn-light' %>
                  </div>
                </div>
                <br>
              <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/spheres/edit_listing.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">

    <div id="edit-form">
        <div class="sphere-form">
          <h1>Edit your sphere's details</h1>
          <div class="mt-3">
                        <div class="row">
                        <div class="col-8">
                              <%= form_for(@sphere) do |f| %>
                                  <div class="form-group">
                                    <%= f.label :title %>
                                    <%= f.text_field :title, class: 'form-control' %>
                                  </div>
                                  <div class="form-group">
                                    <%= f.label :description %>
                                    <%= f.text_field :description, class: 'form-control' %>
                                  </div>
                                  <div class="form-group">
                                    <%= f.label :address %>
                                    <%= f.text_area :address, class: 'form-control' %>
                                  </div>
                                    <div class="form-group">
                                    <%= f.label :price %>
                                    <%= f.number_field :price, class: 'form-control' %>
                                  </div>
<!--                              <div class="form-group">
                                    <%= f.label :barbecue %>
                                    <%= f.radio_button :barbecue, false , :checked => true , :value => false, class: 'form-control' %>
                                  </div> -->
                                  <div class="mt-3">
                                    <%= f.submit "Edit", class: 'btn-yellow' %>
                                    <%= link_to 'Cancel', '#', class: 'btn btn-light' %>
                                  </div>
                              <% end %>
                              </div>
                              <div class="col-4 placing-avatar">
                                <img class="avatar-large" alt="avatar" src="https://images.unsplash.com/photo-1516693452408-b54cfce17899?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" />
                              </div>
                        </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
  <br>

app/views/spheres/index.html.erb
<div id="map_view" class="col-12 map-container">
  <div id="map"
  style="width: 100%; height: 700px;"
  data-markers="<%= @markers.to_json if @markers.present?%>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <button id="list_button" class="btn-yellow flex-item"><p class="button-text">list view</p></button>
</div>

<div class="map-filters">
  <div class="map-filters-toggle">
    <i class="map fas fa-sliders-h"></i>
  </div>
  <%= simple_form_for :search, method: :get do |f| %>
    <div>
      <%= f.check_box :barbecue, { checked: params[:search].present? && params[:search][:barbecue] ? true : false }, true, false %>
      <%= f.label :barbecue, "barbecue" %>
    </div>
    <div>
      <%= f.check_box :balcony, { checked: params[:search].present? && params[:search][:balcony] ? true : false }, true, false %>
      <%= f.label :balcony, "balcony" %>
    </div>
    <div>
      <%= f.check_box :sunny, { checked: params[:search].present? && params[:search][:sunny] ? true : false }, true, false %>
      <%= f.label :sunny, "sunny" %>
    </div>
    <div>
      <%= f.check_box :quiet, { checked: params[:search].present? && params[:search][:quiet] ? true : false }, true, false %>
      <%= f.label :quiet, "quiet" %>
    </div>
    <div>
      <%= f.check_box :garden, { checked: params[:search].present? && params[:search][:garden] ? true : false }, true, false %>
      <%= f.label :garden, "garden" %>
    </div>
    <div>
      <%= f.check_box :terrace, { checked: params[:search].present? && params[:search][:terrace] ? true : false }, true, false %>
      <%= f.label :terrace, "terrace" %>
    </div>
    <div>
      <%= f.check_box :plants, { checked: params[:search].present? && params[:search][:plants] ? true : false }, true, false %>
      <%= f.label :plants, "plants" %>
    </div>
    <div>
      <%= f.check_box :spacious_desk, { checked: params[:search].present? && params[:search][:spacious_desk] ? true : false }, true, false %>
      <%= f.label :spacious_desk, "spaceous desk" %>
    </div>
    <div>
      <%= f.check_box :highspeed_wifi, { checked: params[:search].present? && params[:search][:highspeed_wifi] ? true : false }, true, false %>
      <%= f.label :highspeed_wifi, "highspeed wifi" %>
    </div>
    <div>
      <%= f.check_box :cozy, { checked: params[:search].present? && params[:search][:cozy] ? true : false }, true, false %>
      <%= f.label :cozy, "cozy" %>
    </div>
     <div>
      <%= f.check_box :pet_friendly, { checked: params[:search].present? && params[:search][:pet_friendly] ? true : false }, true, false %>
      <%= f.label :pet_friendly, "pets allowed" %>
    </div>
    <br>
    <div>
      <%= f.check_box :following, { checked: params[:search].present? && params[:search][:following] ? true : false }, true, false %>
      <%= f.label :following, "hosts that I'm following" %>
    </div>
    <br>
    <div>
      <%= select_tag(:cost_per_day, options_for_select(["below 20", "below 10", "free"], selected: params[:cost_per_day]), :include_blank => "cost per day") %>
    </div>
     <br>
    <%= f.button :submit, 'filter', class: 'btn btn-yellow' %>
  <% end %>




</div>

<div class="overlay"></div>


<div id="list_view" class="col-12 hidden" style="padding-left: 0px; padding-right: 0px;">

        <% @spheres.each do |sphere| %>
          <div class="card-sphere">

        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% if sphere.photos.attached? %>
              <% sphere.photos.each_with_index do |photo, index| %>
                <div class="carousel-item <%='active' if index == 0 %>">
                  <%= cl_image_tag photo.key, height: 250, width: 400, crop: :fill, class: "d-block w-100", alt: "pictures of the apartment" %>
                </div>
              <% end %>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

            <div class="card-sphere-infos">
              <b> <%= link_to sphere.title, sphere_path(sphere) %> </b>
              <p>Located at <%= sphere.address %></p>
              <p>Cost per day: <%= sphere.cost_per_day %>€</p>
            </div>
          </div>
        <% end %>

        <button id="map_button" class="btn-yellow flex-item"><p class="button-text">map view</p></button>
</div>
</div>

app/views/spheres/new.html.erb
<div class="edit-banner"> share your sphere </div>

<div class="container my-4">
  <div id="edit-form">
    <div class="mt-3">
      <div class="row">
        <div class="col-12">
          <%= simple_form_for(@sphere) do |f| %>
            <div class="form-group">
              <%= f.label :title, class: "lowercase" %>
              <%= f.text_field :title, class: 'form-control', placeholder: ' Sunny rooftop terrace...' %>
            </div>

            <div class="form-group">
              <%= f.label :description, class: "lowercase" %>
              <%= f.text_field :description, class: 'form-control', placeholder: ' Enjoy the warm summer vibes...' %>
            </div>

            <div class="form-group">
              <%= f.label :address, class: "lowercase" %>
              <%= f.text_area :address, class: 'form-control', placeholder: ' 1 Paradise Road, Berlin...' %>
            </div>

            <div class="form-group">
              <%= f.label :cost_per_day, class: "lowercase" %>
              <%= f.number_field :cost_per_day, class: 'form-control', placeholder: " €" %>
            </div>

            <div class="form-group lowercase">
              <%= f.label :photos %>
              <%= f.input :photos, as: :file, input_html: { multiple: true }, class: 'form-control', label: false %>
            </div>

            <div class="form-check">
              <%= f.check_box :balcony, class:"form-check-input" %>
              <%= f.label :balcony, class: "lowercase form-check-label" %>
            </div>

            <div class="form-check">
              <%= f.check_box :garden, class:"form-check-input" %>
              <%= f.label :garden, class: "lowercase form-check-label" %>
            </div>

            <div class="form-check">
              <%= f.check_box :terrace, class:"form-check-input" %>
              <%= f.label :terrace, class: "lowercase form-check-label" %>
            </div>

            <div class="form-check">
              <%= f.check_box :sunny, class:"form-check-input" %>
              <%= f.label :sunny, class: "lowercase form-check-label" %>
            </div>

            <div class="form-check">
              <%= f.check_box :highspeed_wifi, class:"form-check-input" %>
              <%= f.label :highspeed_wifi, class: "lowercase form-check-label" %>
            </div>

            <div class="form-check">
              <%= f.check_box :plants, class:"form-check-input" %>
              <%= f.label :plants, class: "lowercase form-check-label" %>
            </div>

            <div class="form-check">
              <%= f.check_box :quiet, class:"form-check-input" %>
              <%= f.label :quiet, class: "lowercase form-check-label" %>
            </div>

            <div class="form-check">
              <%= f.check_box :spacious_desk, class:"form-check-input"%>
              <%= f.label :spacious_desk, class: "lowercase form-check-label" %>
            </div>

            <div class="form-check">
              <%= f.check_box :barbecue, class:"form-check-input" %>
              <%= f.label :barbecue, class: "lowercase form-check-label" %>
            </div>

            <div class="form-check">
              <%= f.check_box :cozy, class:"form-check-input" %>
              <%= f.label :cozy, class: "lowercase form-check-label" %>
            </div>

            <div class="form-check">
              <%= f.check_box :pet_friendly, class:"form-check-input"%>
              <%= f.label :pet_friendly, class: "lowercase form-check-label" %>
            </div>

            <div class="mt-3">
              <div class="d-flex justify-content-around">
                <%= f.submit "add", class: 'btn-yellow' %>
                <%= link_to 'cancel', spheres_path, class: 'btn-light' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spheres/new_listing.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">

    <div id="edit-form">
        <div class="sphere-form">
          <h1 id="header-yellow">Add your sphere's details</h1>
          <div class="mt-3">
                        <div class="row">
                        <div class="col-8">
                              <%= form_for(@sphere) do |f| %>
                                  <div class="form-group">
                                    <%= f.label :title %>
                                    <%= f.text_field :title, class: 'form-control', placeholder: ' Playful and energetic...' %>
                                  </div>
                                  <div class="form-group">
                                    <%= f.label :description %>
                                    <%= f.text_field :description, class: 'form-control', placeholder: ' Playful and energetic...' %>
                                  </div>
                                  <div class="form-group">
                                    <%= f.label :address %>
                                    <%= f.text_area :address, class: 'form-control', placeholder: ' Isle of sphere, 1 pet road...' %>
                                  </div>
                                    <div class="form-group">
                                    <%= f.label :price %>
                                    <%= f.number_field :price, class: 'form-control', placeholder: 0 %>
                                  </div>
                                  <div class="form-group">
                                    <%= f.label :photo %>
                                    <%= f.file_field :photo, class: 'form-control' %>
                                  </div>
                            <!--       <div class="form-group">
                                    <%= f.label :barbecue %>
                                    <%= f.radio_button :barbecue, false , :checked => true , :value => false, class: 'form-control' %>
                                  </div> -->
                                  <div class="mt-3">
                                    <%= f.submit "Add", class: 'btn-yellow' %>
                                    <%= link_to 'Cancel', spheres_path, class: 'btn btn-light' %>
                                  </div>
                              <% end %>
                              </div>
                              <div class="col-4 placing-avatar">
                                <img class="avatar-large" alt="avatar" src="https://images.unsplash.com/photo-1529776180807-ea0ee08c8315?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" />
                              </div>
                        </div>
                </div>
            </div>

        </div>
      </div>
    </div>
  </div>
  <br>

app/views/spheres/show.html.erb
<div class="spheres-container">
<!--   <div class="row">
    <div class="col-12 m-auto"> -->

      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% if @sphere.photos.attached? %>
            <% @sphere.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%='active' if index == 0 %>">
                <%= cl_image_tag photo.key, height: 250, width: 400, crop: :fill, class: "d-block w-100", alt: "pictures of the apartment" %>
              </div>
            <% end %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div class="card-sphere-show">
        <div class="card-sphere-show-infos" style="border-bottom: 1px solid lightgray;">
          <div>
            <h1 id="showpage_title">welcome to your <%= @sphere.title.downcase %></h1>
            <br>
            <p> <i class="fas fa-map-marker-alt"></i>  <%= @sphere.address.downcase %></p>
            <p> <i class="far fa-comment"></i>  <%= @sphere.description.downcase %></p>

            <p id="showpage_price"> <i class="fas fa-euro-sign"></i>  <%= @sphere.cost_per_day %>/day</p>
            <br>

            <div>
              <% if @sphere.balcony %>
              <p> balcony </p>
              <% end %>

              <% if @sphere.garden %>
              <p> garden </p>
              <% end %>

              <% if @sphere.terrace %>
              <p> terrace </p>
              <% end %>

              <% if @sphere.sunny %>
              <p> sunny </p>
              <% end %>

              <% if @sphere.highspeed_wifi %>
              <p> highspeed wifi </p>
              <% end %>

              <% if @sphere.plants %>
              <p> plants </p>
              <% end %>
              <% if @sphere.quiet %>
              <p> quiet </p>
              <% end %>
              <% if @sphere.spacious_desk %>
              <p> spacious desk </p>
              <% end %>
              <% if @sphere.barbecue %>
              <p> barbecue </p>
              <% end %>
              <% if @sphere.cozy %>
              <p> cozy </p>
              <% end %>
              <% if @sphere.pet_friendly %>
              <p> pet friendly </p>
              <% end %>
            </div>
          <br>

        <div class="d-flex justify-content-around">
            <% if policy(@sphere).edit? %>
              <%= link_to "edit",  edit_sphere_path,  class: "btn-yellow" %>
            <% end %>
            <% if policy(@sphere).destroy? %>
            <%= link_to "delete", sphere_path(@sphere), class: "btn-yellow", method: :delete, data: { confirm: 'Are you certain you want to delete this?' }%>
            <% end %>
        </div>

        <div class="d-flex justify-content-around">
            <% if @sphere.user != current_user %>
            <%= link_to "go back", spheres_path,  class: "btn-yellow" %>
            <%= link_to "book",  new_sphere_booking_path(@sphere), class: "btn-yellow" %>
            <% end %>
        </div>
        </div>
      </div>
      </div>

      <div class="card" style="border: none; padding: 0px 0px;">
        <div class="card-body" style="text-align: left;">
          <h4 class="card-title">reviews:</h4>
        </div>
        <% if @bookings.present? %>
          <ul class="list-group list-group-flush">
            <% @bookings.each do |booking| %>
              <% if booking.review.present? %>
                <li class="list-group-item"><%= "☀ " * booking.review.rating %><br><em>"<%= booking.review.description %>"</em></li>
              <% end %>
            <% end %>
          </ul>

        <%else%>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">no reviews yet.</li>
          </ul>
        <% end %>






        <div class="card-body d-flex justify-content-center">
          <%= link_to 'continue search', spheres_path, class: 'btn btn-light' %>
        </div>
      </div>

         <br>

        <% if @sphere.user == current_user %>
        <br>
        <% else %>

          <div class="card lowest" style="border: none; padding: 16px; border-top: 1px solid lightgray;">
            <h4 style="margin-top: 5px;"> meet your host: <%= link_to @sphere.user.name, user_path(@sphere.user), style: 'font-weight: bolder; font-size: 24px; text-decoration: none;' %> </h4>
              <br>

               <%= link_to sphere_chatrooms_path(@sphere), method: :post, class: 'd-flex justify-content-around align-items-center btn btn-light' do %>
                <img src="<%= @sphere.user.image %>" class="card-sphere-user avatar-bordered" alt="avatar of user" />
                <p>ask the host a question</p>
                <% end %>

               </div>
        <% end %>

            <!-- <a href="mailto:hello@balconia.xyz"><%= @sphere.user.email %></a> -->
          </div>
         <br>

    </div>
 </div>